package TestScriptsAnxiety;

import BaseAnxietyClasses.BaseTestAnxiety;
import generics.map;
import org.testng.annotations.Test;

public class TestScript1 extends BaseTestAnxiety {
    @Test
    public void chatBotInteraction() {
        map.addDataIntoMap("credentials");
        //response("name");
        response("testname");
        waitingFor(".//span[text()='Yes']");
        yesText();
        waitUntil("health practitioner");
        yeahWithText();
        waitingFor(".//button[@title=\"Depression\"]");
        anxiety();
        System.out.println("Anxiety Option Selected");
        waitUntil("physical health conditions you are");
        hypertension();
        waitUntil("loss of loved one");
        map.addDataIntoMap("anxietypathway");
        response("input1");
        waitUntil("worst possible scenario");
        response("input2");
        waitUntil("interpersonal relationships");
        response("input3");
        waitUntil("coping skills can also get hampered");
        response("input4");
        waitUntil("challenging beliefs");
        response("input5");
        waitUntil("Was this helpful?");
        yes();
        waitUntil("When you thought the bot will make you feel relaxed but instead starts asking uncomfortable questions");
        response("input6");
        waitUntil("volunteering");
        response("input7");
        waitUntil("positive mindset");
        response("input8");
        waitUntil("wrong pronouns");
        //female //others //transgenders
        male();
        waitUntil("So moving on, can you tell me would you like to:");
        continueWithHealoBot();
        waitUntil("like to do next?");
        goInDepth();
        waitUntil("Okay so tell me, do you want to work on:");
        theIssueItself();
        System.out.println("Main Flow ends and the issue opens");
        //session 1 starts
        System.out.println("Session 1 Starts");
        System.out.println("Anxiety Pathway Starts");
        waitUntil("Would you like to work on it?");
        button("(.//button[@title='Yes'])[2]");
        //yes();
        waitUntil("Have you been experiencing similar roadblocks in your life?");
        unabletostayfocused();
        waitUntil("small amount of anxiety");
        response("input9");
        waitUntil("heal is to explore");
        response("input10");
        waitUntil("fatigue and brain fog");
        response("input11");
        waitUntil("Do you want to learn more about it?");
        //yes();
        button("(.//button[@title='Yes'])[3]");
        waitUntil("explore how methylation of DNA");
        //yes();
        button("(.//button[@title='Yes'])[4]");
        waitUntil("Do you also feel chronically fatigued");
        //yes();
        button("(.//button[@title='Yes'])[5]");
        waitUntil("Do you want to know about the details of how it happens?");
        //yes();
        button("(.//button[@title='Yes'])[6]");
        waitUntil("Also do you experience gut as well as sleep issues ?");
        button("(.//button[@title='Yes'])[7]");
        //yes();
        waitUntil("body parts where you felt tension");
        response("input12");
        waitUntil("when in an anxious state");
        feelingnervousorrestless();
        waitUntil("emotions that you feel when anxious");
        response("input13");
        waitUntil("anxiety-laden circumstances");
        response("input14");
        waitUntil("lifestyle habit that keeps you anxious");
        response("input15");
        waitUntil("food your anxiety increases");
        response("input16");
        waitUntil("So, do you feel better now?");
        response("input17");
        waitUntil("visualisation technique");
        response("input18");
        waitUntil("more personalised information");
        yesihavediagnosis();
        waitUntil("Agoraphobia Separation anxiety");
        generalisedanxietydisorder();
        waitUntil("based on the comorbidities");
        Depression();
        waitUntil("physical problems are related to anxiety?");
        NO();//yes
        waitUntil("Anything comes to your mind?");
        response("input19");
        //feedbackPathway();
        waitUntil("session was helpful");
        button(".//button[@title='Strongly Agree']");
        waitUntil("worked for you");
        button(".//button[@title='New perspective']");
        waitUntil("tackle these");
        button(".//button[@title='COME BACK LATER']");
        waitUntil("overwhelming but you");
        System.out.println("Session 1 ends");
        driver.navigate().refresh();
        //session 2 starts
        System.out.println("Session 2 starts");
        //switchSession();
        waitUntil("exercise we did");
        ienjoyeddoingthem();
        waitUntil("Is there some other feedback you would like to give regarding the exercise?");
        response("input20");
        waitUntil("yourself zoning out and wondering");
        response("input21");
        waitUntil("bothered by uncertainties");
        response("input22");
        waitUntil("faced any such event");
        yes();
        waitUntil("four major fears");
        fearofbeingalone();//fear of death //none //meaningfulness
        waitUntil("parents support your decisions");
        response("input23");
        waitUntil("express yourself freely");
        response("input24");
        waitUntil("spend your free / leisure");
        response("input25");
        //feedbackPathway();
        waitUntil("session was helpful");
        button(".//button[@title='Strongly Agree']");
        waitUntil("worked for you");
        button(".//button[@title='New perspective']");
        waitUntil("tackle these");
        button(".//button[@title='COME BACK LATER']");
        waitUntil("overwhelming but you");
        System.out.println("Session 2 ends");
        //session 3 starts
        System.out.println("Session 3 starts");
        //switchSession();
        waitUntil("exercise we did");
        ienjoyeddoingthem();
        waitUntil("Is there some other feedback you would like to give regarding the exercise?");
        response("input26");
        waitUntil("teacher criticises your presentation");
        response("input27");
        waitUntil("Have you had thoughts along these lines?");
        yes();
        waitUntil("thinking trap manifest");
        response("input28");
        waitUntil("negative prediction tendency");
        response("input29");
        waitUntil("Have you had thoughts along these lines?");
        yes();
        waitingFor("(.//p[contains(text(),'Any emotions that it makes')])[2]");
        response("input30");
        waitUntil("Have you had any of these thoughts before?");
        yes();
        waitingFor("(.//p[contains(text(),'thinking trap manifest')])[3]");
        response("input31");
        waitUntil("previous wins with");
        response("input32");
        waitUntil("Have you had any of these thoughts before?");
        yes();
        waitingFor("(.//p[contains(text(),'thinking trap manifest')])[4]");
        response("input33");
        waitUntil("anxious mind works");
        response("input34");
        waitUntil("anxious thoughts or");
        response("input35");
        waitUntil("Are you aware of any of the fears you might have?");
        response("input36");
        waitUntil("will to handle life");
        yes();
        //feedbackPathway();
        waitUntil("session was helpful");
        button(".//button[@title='Strongly Agree']");
        waitUntil("worked for you");
        button(".//button[@title='New perspective']");
        waitUntil("tackle these");
        button(".//button[@title='COME BACK LATER']");
        waitUntil("overwhelming but you");
        System.out.println("Session 3 ends");
        //session 4 starts
        System.out.println("Session 4 starts");
        //switchSession();
        waitUntil("exercise we did");
        ienjoyeddoingthem();
        waitUntil("Is there some other feedback you would like to give regarding the exercise?");
        response("input37");
        waitUntil("panic and anxiety attacks");
        response("input38");
        waitUntil("On this note, do you also experience panic attacks ?");
        yes();
        waitUntil("Would you like to explore panic attacks in detail?");
        yesText();
        waitUntil("greater, inhale");
        response("input39");
        waitUntil("caffeine, nicotine");
        yes();
        waitUntil("overwhelming to recollect");
        response("input40");
        waitUntil("origin in our childhood");
        response("input41");
        waitUntil("cause us to have panic");
        yes();
        waitUntil("acting completely opposite");
        response("input42");
        waitUntil("Do you have any similar experience or story?");
        response("input43");
        waitUntil("desires or fantasies");
        yes();
        waitUntil("autopilot or observing");
        response("input44");
        waitUntil("real reason for ");
        response("input45");
        waitUntil("If you would like to connect with a professional, you can book a session");
        no();//yes
        waitUntil("affirmation or statement");
        response("input46");
        //feedbackPathway();
        waitUntil("session was helpful");
        button(".//button[@title='Strongly Agree']");
        waitUntil("worked for you");
        button(".//button[@title='New perspective']");
        waitUntil("tackle these");
        button(".//button[@title='COME BACK LATER']");
        waitUntil("overwhelming but you");
        System.out.println("Session 4 ends");
        //session 5 starts
        System.out.println("Session 5 starts");
        //switchSession();
        waitUntil("exercise we did");
        ienjoyeddoingthem();
        waitUntil("Is there some other feedback you would like to give regarding the exercise?");
        response("input47");
        waitUntil("develop fear of certain");
        response("input48");
        waitUntil("family ever told");
        response("input49");
        waitUntil("Also, did you have any direct experience of a fearful incident ?");
        response("input50");
        waitUntil("anger, shame or guilt");
        response("input51");
        waitUntil("So do you fear:");
        onlythatparticularride();//all the water parks ride
        waitUntil("explore some specific phobias");
        iamscaredofanysituationplace();//4 options have different options
        waitUntil("certain sensations");
        response("input52");
        waitUntil("Animals? Emptiness");
        response("input53");
        waitUntil("trigger anxiety,");
        response("input54");
        waitUntil("encountered such");
        response("input55");
        waitUntil("relied on by adults");
        yesText();
        waitUntil("connect to a therapist,");
        Continue();
        //feedbackPathway();
        waitUntil("session was helpful");
        button(".//button[@title='Strongly Agree']");
        waitUntil("worked for you");
        button(".//button[@title='New perspective']");
        waitUntil("tackle these");
        button(".//button[@title='COME BACK LATER']");
        waitUntil("overwhelming but you");
        System.out.println("Session 5 ends");
        //session 6 starts
        System.out.println("Session 6 starts");
        //switchSession();
        waitUntil("exercise we did");
        ienjoyeddoingthem();
        waitUntil("Is there some other feedback you would like to give regarding the exercise?");
        response("input56");
        waitUntil("preoccupied with worries");
        response("input57");
        waitUntil("doesn’t make logical sense?");
        response("input58");
        waitUntil("Do you know what 4F is ?");
        yes();//no
        waitUntil("social gathering");
        response("input59");
        waitUntil("Avoiding dogs,");
        response("input60");
        waitUntil("racing heart, breathlessness");
        response("input61");
        waitUntil("SO , do you avoid");
        response("input62");
        waitUntil("e.g. frustration");
        response("input63");
        waitUntil("Let me know which one you have faced in your life:-");
        youfeelemotionlikeguiltshame();//4 other options same connection
        //feedbackPathway();
        waitUntil("session was helpful");
        button(".//button[@title='Strongly Agree']");
        waitUntil("worked for you");
        button(".//button[@title='New perspective']");
        waitUntil("tackle these");
        button(".//button[@title='COME BACK LATER']");
        waitUntil("overwhelming but you");
        System.out.println("Session 6 ends");
        //session 7 starts
        System.out.println("Session 7 starts");
        //switchSession();
        waitUntil("exercise we did");
        ienjoyeddoingthem();
        waitUntil("Is there some other feedback you would like to give regarding the exercise?");
        response("input64");
        waitUntil("differentiating our intuition");
        response("input65");
        waitUntil("overactivated specially if we ");
        response("input66");
        waitUntil("similar experiences, it");
        yesiwouldliketoexplorethat();//nah later
        waitUntil("overactive and supercharged?");
        response("input67");
        waitUntil("overactivation or underactivation");
        response("input68");
        waitUntil("end? Do we have no hope?");
        response("input69");
        waitUntil("Erickson has a whole theory");
        openness();//have options but connection same
        waitUntil("facilitating and guiding");
        noletscontinue();
        waitUntil("On this note, who do you think you need to forgive?");
        Myself();//2 different paths others and universe
        //feedbackPathway();
        waitUntil("session was helpful");
        button(".//button[@title='Strongly Agree']");
        waitUntil("worked for you");
        button(".//button[@title='New perspective']");
        waitUntil("tackle these");
        button(".//button[@title='COME BACK LATER']");
        waitUntil("overwhelming but you");
        System.out.println("Session 7 ends");
        //session 8 starts
        System.out.println("Session 8 starts");
        //switchSession();
        waitUntil("exercise we did");
        ienjoyeddoingthem();
        waitUntil("Is there some other feedback you would like to give regarding the exercise?");
        response("input70");
        waitUntil("Do you know that our gut has a brain of its own?");
        response("input71");
        waitUntil("other caffeine substance");
        caffeine();//alcohol
        waitingFor(".//strong[contains(text(),'Interesting?')]");
        response("input72");
        waitUntil("Do you experience similar problems?");
        yesText();//no
        waitUntil("sound off-topic");
        response("input73");
        waitUntil("flourish with anxiety");
        response("input74");
        waitUntil("cause more suffering");
        response("input75");
        waitUntil("So, would you like to explore how to do that?");
        yesText();//no
        waitUntil("Would you like to");
        accessresourcestohelpyoufurther();//book a session with therapist
        //feedbackPathway();
        waitUntil("session was helpful");
        button(".//button[@title='Strongly Agree']");
        waitUntil("worked for you");
        button(".//button[@title='New perspective']");
        waitUntil("tackle these");
        button(".//button[@title='COME BACK LATER']");
        waitUntil("overwhelming but you");
        System.out.println("Session 8 ends");
        //session 9 starts
        System.out.println("Session 9 starts");
        //switchSession();
        waitUntil("exercise we did");
        ienjoyeddoingthem();
        waitUntil("Is there some other feedback you would like to give regarding the exercise?");
        response("input76");
        waitUntil("So, would you like to explore them?");
        yes();//no
        waitUntil("underlying belief");
        response("input77");
        waitUntil("Would you like to explore this perspective in much more detail?");
        yes();//no
        waitUntil("played out in your particular");
        yes();//no
        waitUntil("we are not able to voice it");
        response("input78");
        waitUntil("energy states is relatively short");
        yes();//no
        waitUntil("energies, in spirituality");
        yes();//no
        waitUntil("From the picture can you guess which of your chakra can be imbalanced?");
        response("input79");
        waitUntil("little about how anxiety");
        yescountmein();//no its not my cup of tea
        //feedbackPathway();
        waitUntil("session was helpful");
        button(".//button[@title='Strongly Agree']");
        waitUntil("worked for you");
        button(".//button[@title='New perspective']");
        waitUntil("tackle these");
        button(".//button[@title='COME BACK LATER']");
        waitUntil("overwhelming but you");
        System.out.println("Session 9 ends");
        System.out.println("Medical Perspective Session Starts");
        waitUntil("Would you like to learn more about how stress affects our immunity?");
        yes();
        waitUntil("So, let me know if you suffer from any of the following physical problems:");
        irritablebowelsyndrome();//different options different paths
        waitUntil("IBS is rarely diagnosed");
        recurrentabdominalpain();
        waitUntil("Would you like to explore the connection between the brain and gut in detail?");
        yes();//no
        //feedbackPathway();
        waitUntil("session was helpful");
        button(".//button[@title='Strongly Agree']");
        waitUntil("worked for you");
        button(".//button[@title='New perspective']");
        waitUntil("tackle these");
        button(".//button[@title='COME BACK LATER']");
        waitUntil("overwhelming but you");
        System.out.println("Medical Perspective Session ends");
        System.out.println("Anxiety Pathways tested successfully");
    }

}
