package TestScriptsDepression;

import BaseDepressionClasses.BaseTestDepression;
import generics.map;
import org.testng.annotations.Test;

public class TestScript1 extends BaseTestDepression {
    @Test
    public void chatBotInteraction(){
        map.addDataIntoMap("credentials");
        response("name");
        waitingFor(".//span[text()='Yes']");
        yesText();
        waitUntil("health practitioner");
        yeahWithText();
        waitingFor(".//button[@title=\"Depression\"]");
        System.out.println("Depression Option Selected");
        depression();
        waitUntil("physical health conditions you are");
        hypertension();
        waitUntil("loss of loved one");
        map.addDataIntoMap("depressionpathway");
        response("input1");
        waitUntil("numb and disconnected");
        response("input2");
        waitUntil("interpersonal relationships");
        response("input3");
        waitUntil("coping with everything");
        response("input4");
        waitUntil("challenging beliefs");
        response("input5");
        waitingFor("(.//div[@class='ac-container'])[4]");
        yes();
        waitingFor("(.//div[@class='ac-container'])[5]");
        response("input6");
        waitUntil("volunteering");
        response("input7");
        waitUntil("positive mindset");
        response("input8");
        waitUntil("wrong pronouns");
        //waitingFor("(.//div[@class='ac-container'])[6]");
        male();
        waitUntil("So moving on, can you tell me would you like to:");
        //waitingFor("(.//div[@class='ac-container'])[7]");
        continueWithHealoBot();
        waitUntil("like to do next?");
        goInDepth();
        waitUntil("Okay so tell me, do you want to work on:");
        theIssueItself();
        System.out.println("Main Flow ends and the issue opens");
        //session 1 starts
        System.out.println("Session 1 Starts");
        System.out.println("Depression Pathway Starts");
        waitUntil("considered individually");
        response("input9");
        waitUntil("those people");
        response("input10");
        waitUntil("grounded and centered");
        yes();
        waitUntil("begin by");
        noDiagnosis();
        waitUntil("Dysthymia");
        majorDepression();
        waitUntil("details as this");
        response("input11");
        waitUntil("incorrect diagnosis");
        borderlineDisorder();
        waitUntil("wired differently");
        response("input12");
        waitUntil("checklist with");
        highAnxiety();
        waitUntil("Do you think something like this might be happening with you as well?");
        yeahAllTheTime();
        waitUntil("Moving on, I’d like to know, did you develop a thought pattern that led you to believe you were up to no good?");
        yeahThatSoundsLikeMe();
        waitUntil("ignoring your pain?");
        response("input13");
        waitUntil("logic applies");
        yesAbsolutely();
        waitUntil("happened to you");
        yesMostOfTheTime();
        waitUntil("ever tried to");
        no();
        feedbackPathway();
        System.out.println("Session 1 ends");
        //session 2 starts
        System.out.println("Session 2 starts");
        switchSession();
        waitUntil("exercise we did");
        ireallyenjoydoingthem();
        waitUntil("any other");
        response("input14");
        waitUntil("being so pessimistic");
        yesallthetime();
        waitUntil("artistic way");
        response("input15");
        waitUntil("Isn’t that right?");
        yesOfCourse();
        waitUntil("altered sleeping");
        response("input16");
        waitUntil("can be overwhelming");
        response("input17");
        waitUntil("Yet, this protective evolutionary system frequently produces unpleasant emotions including dissatisfaction, sadness, grief, fear, anxiety, fury, and guilt. Do you also feel this way?");
        response("input18");
        waitUntil("self-destructive");
        yesmostoftheTimes();
        waitUntil("resonate with");
        ummYeah();
        waitUntil("So, why do you think this happens?");
        idkenlightenme();
        waitUntil("Are you with me so far?");
        yaiseemtogetit();
        waitUntil("strong sense of");
        yeahTotally();
        feedbackPathway();
        System.out.println("Session 2 ends");
        //session 3
        System.out.println("Session 3 starts");
        switchSession();
        waitUntil("exercise we did");
        ireallyenjoydoingthem();
        waitUntil("any other");
        response("input19");
        waitUntil("afraid of being");
        yesText();
        waitUntil("Do you feel like your experience is the same?");
        yesmaybeWithText();
        waitUntil("feel guilty");
        yesText();
        waitUntil("increased appetite");
        yesText();
        waitUntil("winter blues and");
        yesText();
        waitUntil("intensity because");
        yesText();
        waitUntil("depressive symptoms");
        yesText();
        waitUntil("natural process");
        yesText();
        waitUntil("sexual, dirty");
        yesText();
        waitUntil("hormonal changes");
        yesText();
        waitUntil("blues and not of");
        yesItsBabyBlues();
        feedbackPathway();
        System.out.println("Session 3 ends");
        //session 4
        System.out.println("Session 4 starts");
        switchSession();
        waitUntil("exercise we did");
        ireallyenjoydoingthem();
        waitUntil("feedback you would like");
        response("input20");
        waitUntil("Have you heard about them before?");
        yesText();
        waitUntil("If I were to ask you, who/what do you turn to in those times?");
        iIsolateMyself();
        waitUntil("overly revved");
        yesText();
        waitUntil("unrestrained shopping sprees");
        yeahNotSure();
        waitUntil("repetitively have obsessive");
        mayBeSomeTimes();
        waitUntil("you engage");
        youAreLikelyToTakeThingsPersonally();
        waitUntil("Also, do you feel the pressure to always be perfect or guilty if you are not helping others all the time?");
        response("input21");
        waitUntil("you tend to");
        yesText();
        feedbackPathway();
        System.out.println("Session 4 ends");
        //session 5
        System.out.println("Session 5 starts");
        switchSession();
        waitUntil("exercise we did");
        ireallyenjoydoingthem();
        waitUntil("feedback you would like");
        response("input22");
        waitUntil("sense anger inside");
        response("input23");
        waitUntil("especially the ones");
        noNotReally();
        waitUntil("experience rejection");
        response("input24");
        waitUntil("narcissistic or neglectful");
        yesText();
        waitUntil("state wherein");
        mayBeIDK();
        waitUntil("On this note, who do you think you need to forgive?");
        myself();
        feedbackPathway();
        System.out.println("Session 5 ends");
        //session 6
        System.out.println("Session 6 starts");
        switchSession();
        waitUntil("exercise we did");
        ireallyenjoydoingthem();
        waitUntil("feedback you would like");
        response("input25");
        waitUntil("So, would you like to explore them?");
        yesText();
        waitUntil("norm in our");
        response("input26");
        waitUntil("work with energies");
        yesText();
        waitUntil("in spirituality,");
        response("input27");
        waitUntil("feel ungrounded");
        response("input28");
        waitUntil("yourself authentically");
        response("input29");
        waitUntil("self-esteem");
        response("input30");
        waitUntil("connected to Ayurveda");
        noItsNotMyCupOfTea();
        feedbackPathway();
        System.out.println("Session 6 ends");
        //session 7
        System.out.println("Session 7 starts");
        switchSession();
        waitUntil("exercise we did");
        ireallyenjoydoingthem();
        waitUntil("feedback you would like");
        response("input31");
        waitUntil("Do you want to know more about the specifics of this?");
        yesText();
        waitUntil("tested and worked");
        yesyougotitright();
        waitUntil("should be investigated");
        yesText();
        feedbackPathway();
        System.out.println("Session 7 ends");
        //session 8
        System.out.println("Session 8 starts");
        switchSession();
        waitUntil("exercise we did");
        ireallyenjoydoingthem();
        waitUntil("feedback you would like");
        response("input32");
        waitUntil("Do you know that our gut has a brain of its own?");
        response("input33");
        waitUntil("therapy options I");
        response("input34");
        //book a session
        waitingFor(".//span[contains(text(),'Access resources')]");
        accessresourcestohelpyoufurther();
        feedbackPathway();
        System.out.println("Session 8 ends");
    }

}
